### ISSUE TITLE
I do not manage to create generators

### ISSUE THREAD

**Issue by Aspyro** [JDKDigital/generatorgalore#3]
Hello,

I do not manage to create generators.
I am building a relatively simple modpack with AOA3 and Generator Galore, but I do not manage to create generators.
I tried both putting this in the Resource Pack and Data Pack folders. They are recognized, but nothing is added.
Can you spot if I made a mistake ?

Relevant mod information :
- Forge 1.20.1 (47.2.0)
-  Advent Of Ascension 1.20.1-3.6.31
- Generator Galore 1.20.0-1.1.0
- Just Enough Items 15.2.0.27

[aspyrogenerators.zip](https://github.com/JDKDigital/generatorgalore/files/12908991/aspyrogenerators.zip)

**Comment by JaisDK** [comment]
I don't see a json file for the actual generator definition

`resources/data/generatorgalore/generators/limonite.json`

**Comment by Aspyro** [comment]
I just tried adding one, copying data from iron generator.
It did not work either.

Also 
- now I'm wondering as I tried both and none worked, are the new generators supposed to be in Resource packs or in Data Packs ? First time for me making those so i don't really know the difference tbh.
- The file you mentionned to me wasn't there in your exemple folder, that's why I missed it. So i looked up the actual resources files of the mode code, and I didn't spot any other errors I could have made

Could you try and get one version for a limonite generator working ? I'm trying to make an alternative to Iron generator if you need context for actual data.

Thanks

**Comment by JaisDK** [comment]
I forgot how my own mod works, the generator file has to be in the config folder but not a config folder inside the datapack as you have it. In your instance folder there's a config folder, put it in there.

**Comment by Aspyro** [comment]
With that changed, I have the block up and working.
But not the resources (lang/textures/model). If it only were the textures/models i'd feel like I made another mistake, but even the lang file does not work ...
I tried dropping the folder in the 3 locations: data pack, resource pack, config folder. None seemed to work
One fix at a time x)

**Comment by JaisDK** [comment]
resources probably need to be in a resource pack inside the resourcepacks folder instead of together with the datapack stuff

[limonite_generator_resourcepack.zip](https://github.com/JDKDigital/generatorgalore/files/12918640/limonite_generator_resourcepack.zip)

[limonite_generator_datapack.zip](https://github.com/JDKDigital/generatorgalore/files/12918644/limonite_generator_datapack.zip)

**Comment by Aspyro** [comment]
There we go ! It works now !
It needed still a little bit of changes here and there, but we made it work x)
Maybe I'll write later today in another comment the whole folder structure with tips I find useful for first timer like me
Thanks for your help, I appreciate it
![image](https://github.com/JDKDigital/generatorgalore/assets/37420016/144690a8-1825-4e2b-a48a-f0d29ab639ad)

**Comment by Aspyro** [comment]
So, there are 3 parts to complete to have a working generator :
1. Define the generator : this is done by creating a .json file with the name of your generator in the existing config folder. There you will need to put properties about your generator : `generationRate`, `transferRate`, `consumptionRate`, `previousTier` (if needed), `bufferCapacity`, `fuelType` and `fuelTag` or `fuelList` (if needed). Note: Are there other valid properties ?
2. Inside `resourcepacks` folder, define the following assets : `blockstates`, `lang` and `models` for the block and item (don't forget about the upgrade item if one is needed). Note : give an example of resourcepack that works
3. Inside `save\...\datapack` folder, define the following data : `loot_tables`, `recipes` and minecraft `tags`. 
Note : give an example of datapack that works.

Global folder structure : 
```
.minecraft\
  config\
    generatorgalore\
      generators\
        yourcustomgenerator.json
  resourcepacks\
    customgeneratorfoldername\
      assets\
        generatorgalore\
          blockstates\
            yourcustomgenerator_generator.json
          lang\
            en_us.json
          models\
            block\
              yourcustomgenerator_generator_on.json
              yourcustomgenerator_generator.json
            item\
              before_to_yourcustomgenerator_upgrade.json
              yourcustomgenerator.generator.json
  saves\
    yoursave\
      datapacks\
        customgeneratorfoldername\
          data\
            generatorgalore\
              loot_tables\
                blocks\
                  yourcustomgenerator_generator.json
              recipes\
                generators\
                  yourcustomgenerator.json
                upgrades\
                  before_to_yourcustomgenerator_upgrade.json
            minecraft\
              tags\
                blocks\
                  mineable\
                    pickaxe.json
```

Yet another note : How will that work for the datapack when publishing/sharing the structure ? What with the datapack ?
