### ISSUE TITLE
Crash when crafting a crafting table

### ISSUE THREAD

**Issue by GamingZena** [JDKDigital/generatorgalore#5]
The game crashed whilst unexpected error
Error: net.minecraftforge.fml.ModLoadingException: Generator Galore (generatorgalore) encountered an error during the done event phase

**Comment by JaisDK** [comment]
can you provide a full log please or at least the crash report

**Comment by GamingZena** [comment]
https://mclo.gs/0ZODYHG

**Comment by JaisDK** [comment]
are you in creative mode when it happens?

**Comment by GamingZena** [comment]
no im in survival mode im using ATM 9 version 2.37

**Comment by JaisDK** [comment]
did you update generator galore yourself? that version of ATM9 does not have the update with the honey generator

**Comment by GamingZena** [comment]
thats probably why i use Gportal and they only have 2.37 version i did have 2.39 installed on curse its probably not deleted when i downgraded

**Comment by JaisDK** [comment]
ok, go delete the folder `config/generatorgalore/generators` and see if that helps or just the `honey.json` file inside that folder

**Comment by GamingZena** [comment]
alright ill try that now thank you

**Comment by GamingZena** [comment]
i think what it was, i was on version 2.39 and downgraded and it did not delete them certain files now ive done that its all working thank you for the help
