### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Karmas-Daemon** [JDKDigital/generatorgalore#6]
Hello JaisDK,

I have a crash to report found in ATM9, where generator galore appears to be the culprit. Could you help identify the cause, if this is in fact caused by generator galore or who caused it and how it can be fixed?

Crash appears to be random. Occurs while within inventory, refined storage crafting grid ui, botany pots ui, etcetera.  Please see the pastebin bellow.

https://pastebin.com/662ukheu

**Comment by JaisDK** [comment]
Try this

https://github.com/JDKDigital/generatorgalore/issues/5#issuecomment-1910901798

**Comment by Karmas-Daemon** [comment]
I did this. Continued to play all night without crash. So, appears fixed. Thank you, JaisDK!!
