### ISSUE TITLE
[Bug]: Iron Generator does not drop when mined (Neoforge) 

### ISSUE THREAD

**Issue by ThatElektrika** [JDKDigital/generatorgalore#7]
I mined with an iron pickaxe and it didn't drop. I only just started this world so I dont know if it happens to any of the other ones yet.

**Comment by JaisDK** [comment]
What version are you on? 1.21?

**Comment by ThatElektrika** [comment]
Yep, 1.21, latest mod version

**Comment by halvalla01** [comment]
It drops for me, but the content doesn't drop. As in stick some coal in the generator and mine it - the generator drops but the content is voided
