### ISSUE TITLE
nether star generator uses wrong nether star tag(1.21 NeoForge)

### ISSUE THREAD

**Issue by FResetFrisk** [JDKDigital/generatorgalore#9]
![image](https://github.com/user-attachments/assets/aa50966a-3be6-487c-a3a1-c4900411540b)

title pretty much. the nether star generator  uses the wrong nether star tag of "forge:nether_stars" when it should be "c:nether_stars" because of Neoforge changing the tags from forge:"insert item name" to c:"insert item name"

**Comment by JaisDK** [comment]
it's fixed but you need to clear the mods config folder
